import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <Link href="/">Home</Link> 
            <br></br>
            <Link href="/about">About</Link>
            <br></br>
            <Link href="/projects">Projects</Link>
            <br></br>
            <Link href="/contact">Contacts</Link>
            <br></br>
          </nav>
        </header>
        {children}
        <footer>Created at Codex</footer>
        
        </body>
    </html>
  );
}
